# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 06:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikeshell', '0002_auto_20171118_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='bought_tickets',
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 18, 14, 22, 13, 326000)),
        ),
        migrations.AlterField(
            model_name='show',
            name='likes',
            field=models.BigIntegerField(default=1540),
        ),
        migrations.AlterField(
            model_name='show',
            name='stars',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='show',
            name='views',
            field=models.BigIntegerField(default=2420),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 18, 14, 22, 13, 331000)),
        ),
    ]
