# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 06:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikeshell', '0004_auto_20171118_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='show_hosted',
            field=models.ManyToManyField(to='tikeshell.Show'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 18, 14, 39, 49, 843000)),
        ),
        migrations.AlterField(
            model_name='show',
            name='likes',
            field=models.BigIntegerField(default=1072),
        ),
        migrations.AlterField(
            model_name='show',
            name='stars',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='show',
            name='views',
            field=models.BigIntegerField(default=2568),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 18, 14, 39, 49, 849000)),
        ),
    ]
