# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 07:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikeshell', '0007_auto_20171118_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='event',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='seller',
        ),
        migrations.DeleteModel(
            name='showtype',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 18, 15, 7, 23, 747000)),
        ),
        migrations.AlterField(
            model_name='show',
            name='likes',
            field=models.BigIntegerField(default=1869),
        ),
        migrations.AlterField(
            model_name='show',
            name='stars',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='show',
            name='views',
            field=models.BigIntegerField(default=2993),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 18, 15, 7, 23, 754000)),
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
