# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikeshell', '0008_auto_20171118_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category_title',
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 18, 15, 13, 16, 235000)),
        ),
        migrations.AlterField(
            model_name='show',
            name='likes',
            field=models.BigIntegerField(default=1871),
        ),
        migrations.AlterField(
            model_name='show',
            name='views',
            field=models.BigIntegerField(default=2450),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 18, 15, 13, 16, 241000)),
        ),
    ]
