# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 03:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikeshell', '0015_auto_20171119_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='introduction',
            field=models.TextField(default='seller introduction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 11, 6, 24, 165000)),
        ),
        migrations.AlterField(
            model_name='show',
            name='likes',
            field=models.BigIntegerField(default=1084),
        ),
        migrations.AlterField(
            model_name='show',
            name='stars',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='show',
            name='views',
            field=models.BigIntegerField(default=2367),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 11, 6, 24, 172000)),
        ),
    ]
