# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikeshell', '0016_auto_20171119_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 14, 56, 14, 910000)),
        ),
        migrations.AlterField(
            model_name='show',
            name='likes',
            field=models.BigIntegerField(default=1068),
        ),
        migrations.AlterField(
            model_name='show',
            name='stars',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='show',
            name='views',
            field=models.BigIntegerField(default=2243),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 14, 56, 14, 918000)),
        ),
    ]
